# used for development
# docker-compose.override.yml is automatically used by docker-compose when no
# option -f is provided
#
#

version: '2'
services:
  odoo:
    build: ./odoo/
    command: /start.sh
    tty: true
    stdin_open: true
    depends_on:
      - db
    volumes:
      - "data-odoo:/data/odoo"
      - ./odoo/src:/opt/odoo/src
      - ./odoo/local-src:/opt/odoo/local-src
      - ./odoo/external-src:/opt/odoo/external-src
      - ./odoo/songs:/opt/odoo/songs
      - ./odoo/migration.yml:/opt/odoo/migration.yml
      - ./odoo/data:/opt/odoo/data
      - ../env/config:/opt/odoo/etc
      - ../env/log/odoo:/var/log/odoo:rw
      - ../env/start.sh:/start.sh
      - ../env/.pycharm_helpers:/root/.pycharm_helpers/:rw
    environment:
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=mijaebohb8Thae1g
      - RUNNING_ENV=dev
      - ODOO_CONNECTOR_CHANNELS=root:4
      - MARABUNTA_MODE=demo
      - MARABUNTA_ALLOW_SERIE=True
      - SSH_PORT=2223
    ports:
      - 8069
      - 8072
      - 2223:2223

  db:
    image: camptocamp/postgresql:pg9.5-latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  nginx:
    image: camptocamp/odoo-nginx:9.0
    depends_on:
      - odoo
    ports:
      - 80:80

volumes:
  data-odoo:
  data-db:
