# For testers
# This file should be called with
# docker-compose -f docker-compose.yml -f test.yml up

version: '2'
services:
  odoo:
    image: camptocamp/smartliberty_odoo:latest
    environment:
      - MARABUNTA_MODE=demo  # could be 'migration' to run the migration
      - MARABUNTA_ALLOW_SERIE=True  # should not be set in production

  nginx:
    ports:
      - 80:80
      # TODO: 443
