odoo:
  image: camptocamp/smartliberty_odoo:latest
  command: odoo --load=web,web_kanban,attachment_s3,session_redis,logging_json
  tty: true
  external_links:
    - redis-integration/redis:redis
  links:
    - db:db
  environment:
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_PORT=${DB_PORT}
    - ADMIN_PASSWD=${ADMIN_PASSWD}
    - RUNNING_ENV=${RUNNING_ENV}
    - DEMO=${DEMO}
    - WORKERS=${WORKERS}
    - MAX_CRON_THREADS=${MAX_CRON_THREADS}
    - LOG_LEVEL=${LOG_LEVEL}
    - LOG_HANDLER=${LOG_HANDLER}
    - DB_MAXCONN=${DB_MAXCONN}
    - LIMIT_MEMORY_SOFT=${LIMIT_MEMORY_SOFT}
    - LIMIT_MEMORY_HARD=${LIMIT_MEMORY_HARD}
    - LIMIT_REQUEST=${LIMIT_REQUEST}
    - LIMIT_TIME_CPU=${LIMIT_TIME_CPU}
    - LIMIT_TIME_REAL=${LIMIT_TIME_REAL}
    - MARABUNTA_ALLOW_SERIE=True
    - MARABUNTA_MODE=${MARABUNTA_MODE}

    - ODOO_SESSION_REDIS=${ODOO_SESSION_REDIS}
    - ODOO_SESSION_REDIS_HOST=${ODOO_SESSION_REDIS_HOST}
    - ODOO_SESSION_REDIS_PREFIX=${ODOO_SESSION_REDIS_PREFIX}
    - ODOO_SESSION_REDIS_EXPIRATION=${ODOO_SESSION_REDIS_EXPIRATION}
    - ODOO_LOGGING_JSON=${ODOO_LOGGING_JSON}
    - ODOO_CLOUD_PLATFORM_UNSAFE=${ODOO_CLOUD_PLATFORM_UNSAFE}
  labels:
    io.rancher.scheduler.affinity:host_label: application=true,integration=true


db:
  image: camptocamp/postgresql:pg9.5-latest
  environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
  volumes:
    - smartliberty-latest-datadb:/var/lib/postgresql
  labels:
    io.rancher.scheduler.affinity:host_label: application=true,integration=true


nginx:
  image: camptocamp/odoo-nginx:9.0
  links:
    - odoo:odoo
  labels:
    io.rancher.scheduler.affinity:host_label: application=true,integration=true

letsencrypt:
  environment:
    API_VERSION: Production
    AWS_ACCESS_KEY: ${LETSENCRYPT_AWS_ACCESS_KEY}
    AWS_SECRET_KEY: ${LETSENCRYPT_AWS_SECRET_KEY}
    CERT_NAME: ${DOMAIN_NAME}
    CLOUDFLARE_EMAIL: ''
    CLOUDFLARE_KEY: ''
    DNSIMPLE_EMAIL: ''
    DNSIMPLE_KEY: ''
    DOMAINS: ${DOMAIN_NAME}
    DO_ACCESS_TOKEN: ''
    DYN_CUSTOMER_NAME: ''
    DYN_PASSWORD: ''
    DYN_USER_NAME: ''
    EMAIL: letsencrypt@camptocamp.com
    EULA: 'Yes'
    PROVIDER: Route53
    PUBLIC_KEY_TYPE: RSA-2048
    RENEWAL_TIME: '12'
  labels:
    io.rancher.scheduler.affinity:host_label: application=true,integration=true
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  image: janeczku/rancher-letsencrypt:v0.3.0
  volumes:
    - smartliberty-test-certs:/etc/letsencrypt/production/certs
